
["Classic Katana"]
	dash_cooldown = 40.0
	dash_power = 2.0

["Blood Katana"]
	dash_cooldown = 40.0
	dash_power = 2.0
	life-steal = 4.0

["Kurasai Katana"]
	kurasai_katana_lightning_strikes = 2.0
	kurasai_katana_range = 20.0
	buff_power = 4.0
	buff_duration = 20.0
	buff_cdr = 150.0

