
["Attribute 1"]
	enable = true
	display_name = "Damage ยง9โ | ยง9"
	attribute_namespace = "minecraft"
	attribute_name = "generic.attack_damage"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 2"]
	enable = true
	display_name = "Crit % ยง4๐ฏ | ยง4"
	attribute_namespace = "attributeslib"
	attribute_name = "crit_chance"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 10.0

["Attribute 3"]
	enable = true
	display_name = "Crit Dmg ยง4๐ฅ | ยง4"
	attribute_namespace = "attributeslib"
	attribute_name = "crit_damage"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 4"]
	enable = true
	display_name = "Pierce ยง8๐จ | ยง8"
	attribute_namespace = "attributeslib"
	attribute_name = "armor_pierce"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 5"]
	enable = true
	display_name = "Dodge ยง9๐จ | ยง9"
	attribute_namespace = "attributeslib"
	attribute_name = "dodge_chance"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 6"]
	enable = true
	display_name = "HP ยงcโค๏ธ | ยงc"
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 7"]
	enable = true
	display_name = "Healing ยงa๐ | ยงa"
	attribute_namespace = "attributeslib"
	attribute_name = "healing_received"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 8"]
	enable = true
	display_name = "ยงfLuck ยงa๐| ยงa"
	attribute_namespace = "minecraft"
	attribute_name = "generic.luck"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 9"]
	enable = true
	display_name = "MS ยง9๐ | ยง9"
	attribute_namespace = "minecraft"
	attribute_name = "generic.movement_speed"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 10.0

["Attribute 10"]
	enable = true
	display_name = "AS ยง6โก | ยง6"
	attribute_namespace = "minecraft"
	attribute_name = "generic.attack_speed"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 11"]
	enable = true
	display_name = "Knock Res ยง9๐ก | ยง9"
	attribute_namespace = "minecraft"
	attribute_name = "generic.knockback_resistance"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 12"]
	enable = true
	display_name = "Luck ยง9๐ | ยง9"
	attribute_namespace = "minecraft"
	attribute_name = "generic.luck"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 13"]
	enable = true
	display_name = "Arrow Dmg ยง9๐น | ยง9"
	attribute_namespace = "attributeslib"
	attribute_name = "arrow_damage"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 14"]
	enable = true
	display_name = "Draw Speed ยง9๐น | ยง9"
	attribute_namespace = "attributeslib"
	attribute_name = "draw_speed"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 15"]
	enable = false
	display_name = "Drawn Speed ยง9๐น | ยง9"
	attribute_namespace = "attributeslib"
	attribute_name = "arrow_damage"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

