
["Attribute 1"]
	display_name = "Vitality : "
	cmd_to_exc = ["/attribute @p minecraft:generic.max_health base set [param(10.0)]", "effect give @p minecraft:instant_health 20 3"]
	tip_to_display = "§7Increases your maximum health and enhances the effectiveness of healing received."
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 2"]
	display_name = "Power : "
	cmd_to_exc = ["/attribute @p attributeslib:crit_chance base set [param(0.01)]", "/attribute @p attributeslib:crit_damage base set [param(0.015)]", "/attribute @p minecraft:generic.attack_damage base set [param(5.0)]"]
	tip_to_display = "§7Increases the likelihood of critical hits, boosts critical damage, and enhances overall attack damage."
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 3"]
	display_name = "Resilience : "
	cmd_to_exc = ["/attribute @p minecraft:generic.armor base set [param(2.0)]", "/attribute @p attributeslib:dodge_chance base set [param(1)]", "/attribute @p irons_spellbooks:spell_resist base set [param(0.05)]"]
	tip_to_display = "§7Reduces the effectiveness of enemy armor, increases your defense, and grants a chance to dodge attacks."
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 4"]
	display_name = "Ranged Mastery : "
	cmd_to_exc = ["/attribute @p attributeslib:arrow_damage base set [param(0.1)]", "/attribute @p attributeslib:draw_speed base set [param(0.1)]"]
	tip_to_display = "§7Increases the damage dealt by arrows and projectiles and reduces the time needed to draw and fire ranged weapons."
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 5"]
	display_name = "Speed : "
	cmd_to_exc = ["/attribute @p minecraft:generic.attack_speed base set [param(1)]"]
	tip_to_display = "§7Increases your attack speed and boosts the speed at which blocks are mined."
	max_level = 30.0
	base_value_per_point = 1.0
	lock = false

["Attribute 6"]
	display_name = "Arcane Power : "
	cmd_to_exc = ["/attribute @p irons_spellbooks:spell_power base set [param(1)]"]
	tip_to_display = "§7Increases the strength of your spells and reduces the damage taken from enemy spells."
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 7"]
	display_name = "Mana Flow : "
	cmd_to_exc = ["/attribute @p irons_spellbooks:max_mana base set [param(10.0)]", "/attribute @p irons_spellbooks:mana_regen base set [param(0.005)]"]
	tip_to_display = "§7Increases your maximum mana and speeds up mana regeneration."
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 8"]
	display_name = "Casting Efficiency : "
	cmd_to_exc = ["/attribute @p irons_spellbooks:cast_time_reduction base set [param(0.2)]", "/attribute @p irons_spellbooks:cooldown_reduction base set [param(0.2)]"]
	tip_to_display = "§7Reduces the time needed to cast spells and shortens the cooldown between casts."
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 9"]
	cmd_to_exc = ["/attribute @p attributeslib:mining_speed base set [param(0.05)]"]
	max_level = 50.0
	base_value_per_point = 1.0
	lock = false
	"display_name " = ""
	"tip_to_display " = ""

["Attribute 10"]
	cmd_to_exc = [""]
	max_level = 0.0
	base_value_per_point = 0.0
	lock = true
	"display_name " = ""
	"tip_to_display " = ""

