
["Global Settings"]
	lesser_experience_value = 20.0
	better_experience_value = 200.0
	greater_experience_value = 800.0
	#the ammount of levels the orb of leveling gives
	level_per_orb = 1.0
	#the higher it is the harder it is to level up
	xp_diminishing_factor = 20.0
	points_per_level = 1.0
	enable_drops = false
	on_death_reset = false
	max_player_level = 500.0

["Leveling Scale"]
	levels_scale_interval = ["[range]0-50[rangeEnd][scale]1.1[scaleEnd]", "[range]51-100[rangeEnd][scale]1.05[scaleEnd]", "[range]101-200[rangeEnd][scale]1.01[scaleEnd]", "[range]201-500[rangeEnd][scale]1.001[scaleEnd]"]
	#incase you didn't setup a level scale this value will be applied
	levels_scale_default = 1.001
	first_level_xp = 900.0

["Initial Starting Values"]
	init_val_attribute_one = 2.0
	init_val_attribute_two = 1.0
	init_val_attribute_three = 0.0
	init_val_attribute_forth = 10.0
	init_val_attribute_fifth = 4.0
	init_val_attribute_sixth = 0.0
	init_val_attribute_seventh = 10.0
	init_val_attribute_eight = 0.0
	init_val_attribute_nine = 20.0
	init_val_attribute_ten = 0.0
	init_val_starting_level = 1.0

["HUD Overlay"]
	display_level_overlay = true
	display_xp_overlay = true
	display_points_overlay = true
	global_stats_ui_color = "ยง6"

["Artifacts Settings"]
	bonus_experience_factor = 1.4

