
[Blacklist]
	#write the registry name of the entities
	banned = [" "]
	death_messages = false
	locked_mobs = ["500/minecraft:ender_dragon", "250/minecraft:wither", "035/iceandfire:cyclops", "075/iceandfire:ice_dragon", "075/iceandfire:fire_dragon", "iceandfire:lightning_dragon"]
	can_be_ascendant = ["minecraft:zombie", "minecraft:skeleton"]

